server:
  port: 8082
  servlet:
    context-path: /profile
spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678
jwt:
  signerKey: "SgVPo7RxnbP1N+jw9D37irwm2B5FXw5xJmgRMPNkVCkx/8SNT0MUb2xzqx3ZSicc"
  valid-duration: 3600 #in seconds (Thời gian hiệu lực của token)
  refreshable-duration: 360000 #in seconds (Thời gian hiệu lực của token có thể refresh tính từ thời điểm token hết hạn)
